name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - name: Checkout and pnpm
        uses: actions/checkout@v3.3.0
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
          cache-dependency-path: './pnpm-lock.yaml'

      - name: Install Dependencies
        run: pnpm i

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm coverage --no-cache --runInBand

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
